name: CI/CD
on:
  push:
    branches:
      - "!**"
    tags:
      - "**"
  workflow_dispatch:
permissions: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY_B64: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
      SSH_REMOTE_DIR: ${{ secrets.SSH_REMOTE_DIR }}
      SSH_REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
      SSH_REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
      SSH_REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
      WORKING_DIR: ${{ github.workspace }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup ssh
        run: |
          which ssh > /dev/null || (apt-get update -qq && apt-get install -qq openssh-client)
          which rsync > /dev/null || (apt-get update -qq && apt-get install -qq rsync)
          mkdir -p ~/.ssh && chmod 0700 ~/.ssh
          echo "$SSH_PRIVATE_KEY_B64" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
          cp $WORKING_DIR/.ssh/config ~/.ssh/config
      - name: connect and deploy
        run: |
          rsync -ae "ssh -q -p $SSH_REMOTE_PORT" $WORKING_DIR ${SSH_REMOTE_USER}@${SSH_REMOTE_HOST}:${SSH_REMOTE_DIR}/ --exclude ".*" --exclude "production-server/"
          ssh -q -p $SSH_REMOTE_PORT ${SSH_REMOTE_USER}@${SSH_REMOTE_HOST} /start.sh
